branches:
  only:
  - master
language: node_js
node_js:
- 0.10.32
env:
  global:
  - secure: SE0hRL6Aa2sU9yj5gK+7mWudaCYK8ClvP5MHrDMv46Tdn6GwBdEp8RRgV4Ojl0FvQW+jJZUMpSk3Wv1gNXymiTt/xM2fKGQ1kP9V/IuzQo2WwERmonHaQjgfMBrzPa7ur3nVq8npuAWVPaw9GAEVSH/juF7OMJelByFEN5L6mXI=
  - secure: bYoIvqJMvoj2TLxG84o8cfF8JU0BMmiQ1Lzj7IuFLGEurezujn9aMDcqNbEV25bfSbeHB6qlWa4OHx+qQmQJtZ8hXUoF/bSYehnSHaWUVHJ7f+je0kdOVXoVybqzUT58UpYaJN2GMKCfTx/7Ydkiv/9TFt53TbhR4xhKP2Ta4KQ=
  - secure: iLIo9zX9pbsc9GAnxAlyzSNHHbae5N6tKZIf6Y5QEwBmnPK6TT5qeEAieyATd5EZvARAt5Ym2lTTCw91fwFZr5BV1uo0a5O7/J2TEjtBSDnq3zeohDafZohtNgvH/7xoIXadTO8WQ6IH+xuNW/gafYoxUL8us+UiW8rW/cS2OEA=
addons:
  sauce_connect: true
before_install:
- npm install -g gulp
- git config --global user.email USER_EMAIL
- git config --global user.name USER_NAME
install:
- npm install
before_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- echo node_modules/ > .gitignore
script:
- gulp deploy
before_deploy:
- git status
- git add -A
- git commit -m "carrier-pigeon-beta"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: bqUfOXwC0+c8OIeeRrR8xiu8J62s6Iu2I3+rBFA0O0/0yr/8ja6VAv10ZH5tK7PVM786kZVxaUXIA/JrPg49nD4elaDmRsdePTx0nmk+gq47w9z1iVxJsblhqI+gwQMqPBS8gprLS8Ajs1SwhRHT74BjjFxHY/yWhNqJSbMsxck=
  secret_access_key:
    secure: CKsH+zinba82J7suOnMZ0ULFXOQvY1MkfDJ3YU+Uqtl54B/ezXtkDA37jm5NItbOAaLQ3ueWatKOzFVY2iyyFOrVP3QgqoXAWAATgPz48POWOD3KPekmox7vT2usoih7vBfY2L+SVYeTerE56/LSqydQ3rdMbXZsic8hcHQsa+A=
  region: eu-west-1
  app: carrier-pigeon-fac
  env: carrierPigeonFac-env
  bucket_name: carrier-pigeon-1428062159
  on:
    branch: master
