branches:
  only:
  - master
language: node_js
node_js:
- 0.10.32
env:
  global:
  - secure: SE0hRL6Aa2sU9yj5gK+7mWudaCYK8ClvP5MHrDMv46Tdn6GwBdEp8RRgV4Ojl0FvQW+jJZUMpSk3Wv1gNXymiTt/xM2fKGQ1kP9V/IuzQo2WwERmonHaQjgfMBrzPa7ur3nVq8npuAWVPaw9GAEVSH/juF7OMJelByFEN5L6mXI=
  - secure: OYV0Q68p+wMZWw2EpGl/LdqZ1lmnhb16Qv+AMRKnNO3S8TpeFQyRYJ90uya+9dvGN4azhKLjtDQ/QhXIdeIyDz/47Gvj0o8WGiSinnsFeqSNOjN073BiK7r7+7SzgpVTJSR6Jp44D5qh2QZ5qZr9ppJ+3jcc5VXDc2JSCSKjJzE=
  - secure: KFhvXwzrG6KM+ksePLZPLrkjvN4SfgDDetfSpi6At3vkm+kfvmaCL3D++n/rD0Nhztv81yyEKEdbTgoUHP0mZz24qo5LnRITuR3cWvQQtupqBC78jYfV4N0lzL35TbkrA9NUK04BImBAuN3INx1RAquh/Q//3qkyszjHDQep8aY=
addons:
  sauce_connect: true
before_install:
- npm install -g gulp
- git config --global user.email USER_EMAIL
- git config --global user.name USER_NAME
install:
- npm install
before_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- echo node_modules/ > .gitignore
script:
- gulp deploy
before_deploy:
- git status
- git add -A
- git commit -m "carrier-pigeon-beta"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: bqUfOXwC0+c8OIeeRrR8xiu8J62s6Iu2I3+rBFA0O0/0yr/8ja6VAv10ZH5tK7PVM786kZVxaUXIA/JrPg49nD4elaDmRsdePTx0nmk+gq47w9z1iVxJsblhqI+gwQMqPBS8gprLS8Ajs1SwhRHT74BjjFxHY/yWhNqJSbMsxck=
  secret_access_key:
    secure: CKsH+zinba82J7suOnMZ0ULFXOQvY1MkfDJ3YU+Uqtl54B/ezXtkDA37jm5NItbOAaLQ3ueWatKOzFVY2iyyFOrVP3QgqoXAWAATgPz48POWOD3KPekmox7vT2usoih7vBfY2L+SVYeTerE56/LSqydQ3rdMbXZsic8hcHQsa+A=
  region: eu-west-1
  app: carrier-pigeon-fac
  env: carrierPigeonFac-env
  bucket_name: carrier-pigeon-1428062159
  on:
    branch: master
