branches:
  only:
  - master
language: node_js
node_js:
- 0.10.32
env:
  global:
  - secure: SE0hRL6Aa2sU9yj5gK+7mWudaCYK8ClvP5MHrDMv46Tdn6GwBdEp8RRgV4Ojl0FvQW+jJZUMpSk3Wv1gNXymiTt/xM2fKGQ1kP9V/IuzQo2WwERmonHaQjgfMBrzPa7ur3nVq8npuAWVPaw9GAEVSH/juF7OMJelByFEN5L6mXI=
before_install:
- npm install -g gulp
- git config --global user.email USER_EMAIL
- git config --global user.name USER_NAME
install:
- npm install
before_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- echo node_modules/ > .gitignore
script:
- gulp build
before_deploy:
- git status
- git add -A
- git commit -m "carrier-pigeon-beta"
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "IsDxXIPQ/i68tZihBLAcswGN84LrItGcGG2/B/Zjm8N97pDHaWwDlluBWWNCDbNioZEiyDfDb8oqylh8qdKO8H568sIoFAU7T5GRPyePBPYWCJ4P3S2vVxDu13WZfRiZNB/5z65/Srh3gMw/WYIiJgOiNbB/6dCh5eS+VJSYNFs="
  secret_access_key: 
    secure: "EwPzSAJ69KU0K/DbTrnZ1B/vFiVfhwgVH5k2HnIp/fOENRWOec96siYU0IoCQVHPNecxJzGpbRlAWCGGicEhXSYrLCmQgcnzYBEbR1LdU5tBcrXEsrvXvw2d4Z4dEKV6SXZ2IKXCC0vxHeS9MJtlyy0IJiVcUrRJsjSEwD5f58Y="
  region: eu-west-1
  app: carrier-pigeon-fac
  env: carrierPigeonFac-env
  bucket_name: carrier-pigeon-1428062159