branches:
  only:
  - master
language: node_js
node_js:
- 0.10.32
env:
  global:
  - secure: Yr9YkCpVGIIUbyGgdqmb3Xice24W2ypYr5E273KgPJAOvRNmhnzZWLToJt/ZRnZ32SuLUyoYsYpxkx1nYhek4YpmleFao1KXnVyjpUskGgW3/PpJZrEiuu09K6Pjb+vFD6cYL3VBIW3ll+TH9zBX2cUS4ttofS9Rumlx40MR1ZA=
  - secure: SE0hRL6Aa2sU9yj5gK+7mWudaCYK8ClvP5MHrDMv46Tdn6GwBdEp8RRgV4Ojl0FvQW+jJZUMpSk3Wv1gNXymiTt/xM2fKGQ1kP9V/IuzQo2WwERmonHaQjgfMBrzPa7ur3nVq8npuAWVPaw9GAEVSH/juF7OMJelByFEN5L6mXI=
  - secure: KcwwJFeEmvk9lyZgkvwOySU+b9RAsKv6NZ6uMkWK5A+pWOo9VB5AhETUjwEmWWPjkrfsiAb/NrYbBJi3vOqKbvyIGfMp7pNzsYd6rNayAJfI0X0UJC6hWNfuMvnGLWTQcbypdA/C6iEQdrrbi69CoNEVfALl3+JTe/KoRTGBDHA=
  - secure: OxmjBfEBIqjOFnht1OJnkpaojp7aEWjbebMYGJHwk/uOX7HAt0ZvFsr1PmGDbV4XqqFA1siUGXfMQ9mx37LLjB2oTSEgUcQXxFWfTBeVUv4TAwyiI3BATc/W6d4ms/aQCabQeGtjJjBRxvesh/z0nCgGavUIeHY2aW2x0w7CUZw=
before_install:
- npm install -g gulp
- git config --global user.email USER_EMAIL
- git config --global user.name USER_NAME
install:
- npm install
before_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- echo node_modules/ > .gitignore
addons:
  sauce_connect: true
script:
- psql -c 'create database testdb;' -h localhost -p 5432 -U postgres
- gulp deploy
before_deploy:
- git status
- git add -A
- git commit -m "carrier-pigeon-beta"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: bqUfOXwC0+c8OIeeRrR8xiu8J62s6Iu2I3+rBFA0O0/0yr/8ja6VAv10ZH5tK7PVM786kZVxaUXIA/JrPg49nD4elaDmRsdePTx0nmk+gq47w9z1iVxJsblhqI+gwQMqPBS8gprLS8Ajs1SwhRHT74BjjFxHY/yWhNqJSbMsxck=
  secret_access_key:
    secure: CKsH+zinba82J7suOnMZ0ULFXOQvY1MkfDJ3YU+Uqtl54B/ezXtkDA37jm5NItbOAaLQ3ueWatKOzFVY2iyyFOrVP3QgqoXAWAATgPz48POWOD3KPekmox7vT2usoih7vBfY2L+SVYeTerE56/LSqydQ3rdMbXZsic8hcHQsa+A=
  region: eu-west-1
  app: carrier-pigeon-fac
  env: carrierPigeonFac-Se-env
  bucket_name: carrier-pigeon-1428062159
  on:
    branch: master
